### ISSUE TITLE
How to use domain message flow modelling

### ISSUE THREAD

**Issue by asidhu11702** [ddd-crew/domain-message-flow-modelling#3]
Can someone explain how can I use this notation? Is this available in miro boards or lucid charts. I tried few places I couldnt find how to use this chart

**Comment by asidhu11702** [comment]
I didnt find a way so I can use this chart in lucid charts or miro board. can someone help me please with that

**Comment by NTCoding** [comment]
Sorry for the delay, I've been on vacation. Please check this out: https://github.com/ddd-crew/virtual-modelling-templates. Let me know if there is anything else I can do to help.
