### ISSUE TITLE
Notation of a time-dependent message

### ISSUE THREAD

**Issue by MikeBild** [ddd-crew/domain-message-flow-modelling#7]
How about a notation of a time-dependent message? E.g. scenario: cancel an online order after 5 minutes of inactivity

**Comment by NTCoding** [comment]
Hi @MikeBild. Good question.

I would normally show a time-triggered event something like this, although other people may show it differently.

<img width="1033" alt="Screenshot 2021-08-08 at 10 18 54" src="https://user-images.githubusercontent.com/692094/128627216-cc2d834b-1891-4646-a5a5-ad1d3cbf9565.png">

**Comment by MikeBild** [comment]
Thx. Seems doable. Would different semantics make sense here? For example: within 5 minutes, after 5 minutes, every 5 minutes?

**Comment by NTCoding** [comment]
@MikeBild I think it makes sense to be more specific if it's not clear. As you say, add within/after/every to the note.

**Comment by yellowbrickc** [comment]
Added his scenario and the tip to the repo, thank you 🙏
