### ISSUE TITLE
Differentiation between Queries and Views/Responses

### ISSUE THREAD

**Issue by alexlawrence** [ddd-crew/domain-message-flow-modelling#9]
Hi,

IIUC, the pattern language is very similar to EventStorming. In EventStorming, as in Domain Message Flow Modelling, Queries are green-ish stickies. What I don't understand is how to use them for visualizing flows.

Together with a Query, there is always a View or a Response. In my opinion, it can be required/helpful to visualize the two separately. A Query has a certain message body, same as a View/Response.

Would be great if you could explain the intended use in the README, maybe with an example.
Alternatively, if you can explain how it is meant to be, I can also create an MR.

Thanks!

**Comment by NTCoding** [comment]
Hey @alexlawrence. This is a good point, thanks for raising. The docs need a bit of a refresh and I was planning to make some updates when I get time. I'm just a bit busy during this period.

Whenever I want to show the parameters of a request and the schema of a response I usually do something basic like this:
<img width="413" alt="Capture d’écran 2023-05-15 à 13 50 48" src="https://github.com/ddd-crew/domain-message-flow-modelling/assets/692094/1afe28f8-d40d-4298-871e-58b9b36b6be3">

But there are no strict rules. If you have other ideas feel free to share them in here.

**Comment by alexlawrence** [comment]
Thanks for the response. I didn't think of this, that's a good idea. So basically Queries/Responses will appear as one element and the additional context describes the contents of both messages.

Which direction does the arrow go then? I assume from the issuer of a query to the part that receives it, or?

**Comment by NTCoding** [comment]
Sorry for the long delay in replying. I've been travelling a lot through May and June.

Basically, the arrow represents the flow from conversation initiator. So if you view a query message as a question, the arrow goes from the collaborator asking the question to the collaborator that receives the question and responds to it (as you suggested).

Again, sorry for the delay.

**Comment by alexlawrence** [comment]
> Sorry for the long delay in replying. I've been travelling a lot through May and June.

No need to apologize. Thanks for the answer!

**Comment by yellowbrickc** [comment]
Thanks for this discussion @alexlawrence, @NTCoding. I added your proposal (and pic 😆 ) to the readme.
